# Conversion a TensorFlow Lite
Se convierten los modelos de TensorFlow a TensorFlow Lite, generando en cada caso una versión cuantizada y una versión
no cuantizada.
## Imports

In [1]:
from tf_lite_conversion import *

## Parámetros
Parámetros para ajustar la conversión.

In [2]:
project_dir = "/home/daniel/PycharmProjects/tfg-tinyml"

saved_audio_models_dir = f"{project_dir}/saved models/audio"
audio_model_name = f"ExtAudioDataModel"
audio_model_dir = f"{saved_audio_models_dir}/tensorflow"
audio_model_output_dir = f"{saved_audio_models_dir}/tensorflow lite"
audio_representative_dataset_dir = f"{project_dir}/samples/external/audio/train"

saved_image_models_dir = f"{project_dir}/saved models/image"
image_model_name = f"MicroImgDataModel"
image_model_dir = f"{saved_image_models_dir}/tensorflow"
image_model_output_dir = f"{saved_image_models_dir}/tensorflow lite"
image_representative_dataset_dir = f"{project_dir}/samples/microcontroller/preprocessed image/train"

## Carga de datasets representativos
Se cargan los datasets que se usarán para ajustar la cuantización.

In [3]:
image_representative_dataset = get_image_representative_dataset(image_representative_dataset_dir)
audio_representative_dataset = get_audio_representative_dataset(audio_representative_dataset_dir)

Found 274 files belonging to 3 classes.
Using 12924 samples.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.


## Conversión de modelos
Se aplica la conversión de modelos.

In [4]:
convert_saved_model(audio_model_name, audio_model_dir, audio_model_output_dir)
convert_saved_model(audio_model_name, audio_model_dir, audio_model_output_dir, quantize=True,
                    representative_dataset=audio_representative_dataset)
convert_saved_model(image_model_name, image_model_dir, image_model_output_dir)
convert_saved_model(image_model_name, image_model_dir, image_model_output_dir, quantize=True,
                    representative_dataset=image_representative_dataset)

Model converted. The model has been saved in /home/daniel/PycharmProjects/tfg-tinyml/saved models/audio/tensorflow lite/ExtAudioDataModel.tflite.
Applying quantization to ExtAudioDataModel.
Model converted. The model has been saved in /home/daniel/PycharmProjects/tfg-tinyml/saved models/audio/tensorflow lite/ExtAudioDataModelQuant.tflite.
Model converted. The model has been saved in /home/daniel/PycharmProjects/tfg-tinyml/saved models/image/tensorflow lite/MicroImgDataModel.tflite.
Applying quantization to MicroImgDataModel.
tf.Tensor(
[[[[[ 37.]
    [ 38.]
    [ 38.]
    ...
    [ 25.]
    [ 23.]
    [ 21.]]

   [[ 37.]
    [ 38.]
    [ 38.]
    ...
    [ 29.]
    [ 27.]
    [ 26.]]

   [[ 37.]
    [ 38.]
    [ 38.]
    ...
    [ 33.]
    [ 32.]
    [ 31.]]

   ...

   [[ 50.]
    [ 49.]
    [ 48.]
    ...
    [ 50.]
    [ 42.]
    [ 37.]]

   [[ 53.]
    [ 51.]
    [ 49.]
    ...
    [ 45.]
    [ 38.]
    [ 35.]]

   [[ 55.]
    [ 52.]
    [ 49.]
    ...
    [ 44.]
    [ 39.]
    [ 3

RuntimeError: tensorflow/lite/kernels/pad.cc:123 op_context.dims <= reference_ops::PadKernelMaxDimensionCount() was not true.Node number 2 (PAD) failed to prepare.
